language: common-lisp
sudo: false
env:
  global:
  - PATH=~/.roswell/bin:$PATH
  - ROSWELL_INSTALL=$HOME/.roswell

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros test/ci.lisp
